# Nome da aplicação
spring.application.name=demo

# Configuração do Banco H2 (Impede que ele crie bancos aleatórios)
spring.datasource.url=jdbc:h2:mem:petdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.generate-unique-name=false

# Mantém a conexão aberta e permite ver o console do banco
spring.h2.console.enabled=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Mostra no terminal o que o Java está fazendo no banco (ajuda a debugar)
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update